### ISSUE TITLE
Notification update - translation not working properly %{fname} 

### ISSUE THREAD

**Issue by peter-jerry-ye** [benwinding/react-admin-import-csv#39]
According to this [answer](https://stackoverflow.com/questions/54069253/usestate-set-method-not-reflecting-change-immediately), the `setState` won't change the function immediately, thus we can see that in the notification, the translation does not work, because the state remains null.
<img width="1030" alt="截屏2020-11-20 下午3 59 02" src="https://user-images.githubusercontent.com/16731997/99774902-601c3380-2b49-11eb-911d-193bc03da070.png">

**Comment by benwinding** [comment]
Thanks for reporting and fixing the issue @peter-jerry-ye,
Should be deployed in version `1.0.6`
Cheers,
Ben

**Comment by benwinding** [comment]
Thanks for reporting and fixing the issue @peter-jerry-ye,
Should be deployed in version `1.0.6`
Cheers,
Ben

**Comment by peter-jerry-ye** [comment]
> Thanks for reporting and fixing the issue @peter-jerry-ye,
> Should be deployed in version `1.0.6`
> Cheers,
> Ben

Sorry for the confusion, but the pull request wasn't aimed for this issue. The pull request was aimed to allow async preprocess of csv file, but this issue is something else.

**Comment by benwinding** [comment]
Ahh okay, I'll have a look at this in the next few days :+1:

**Comment by benwinding** [comment]
![Peek 2020-11-21 18-39](https://user-images.githubusercontent.com/11782590/99871277-e65b7700-2c28-11eb-9f09-e351a615ba00.gif)

Translation seems to work with Demo here: https://benwinding.github.io/react-admin-import-csv/

Can you show me the configuration you had to reproduce that?

**Comment by peter-jerry-ye** [comment]
The same demo, tested just now. Except my default language is Chinese.

发件人: Ben Winding<mailto:notifications@github.com>
发送时间: 2020年11月21日 16:12
收件人: benwinding/react-admin-import-csv<mailto:react-admin-import-csv@noreply.github.com>
抄送: Zihang Ye<mailto:jerryzihye@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [benwinding/react-admin-import-csv] translation does not work (#39)


[Peek 2020-11-21 18-39]<https://user-images.githubusercontent.com/11782590/99871277-e65b7700-2c28-11eb-9f09-e351a615ba00.gif>

Translation seems to work with Demo here: https://benwinding.github.io/react-admin-import-csv/

Can you show me the configuration you had to reproduce that?

―

**Comment by benwinding** [comment]
Found the exact issue.
- The rendering and state doesn't seem to affect the translations.
- It seems to be the translation library not interpreting Chinese correctly.
![image](https://user-images.githubusercontent.com/11782590/99891803-db9ef180-2cbd-11eb-88dd-5c3ba71ecada.png)
- I replaced a Chinese, translation with an English one in `src/i18n/zh.ts` and the English one worked correctly.
![image](https://user-images.githubusercontent.com/11782590/99891710-d7260900-2cbc-11eb-9a46-27cae3ce289b.png)
- Spanish translations have the same issue :cry: 
![image](https://user-images.githubusercontent.com/11782590/99891782-8a8efd80-2cbd-11eb-843b-6e37546109a5.png)

**Comment by peter-jerry-ye** [comment]
That's interesting. But it's normal for the spanish one not working because there's a space after %.
What I've found was that there's a reset state before the notification. Not sure if that's relavent.

YE Zihang
________________________________

**Comment by benwinding** [comment]
Found the issue, turns out was a simple uni-code character mismatch, from copying from Google Translate, it didn't use the correct `%` sign!!
![image](https://user-images.githubusercontent.com/11782590/99891862-62ec6500-2cbe-11eb-9e65-daba839560d3.png)
Should be working now, that was a silly bug :laughing:

**Comment by peter-jerry-ye** [comment]
Thank you for your great work!

But unfortunately one problem still remains: the problem with the notification.
I've just tested with your most recently deployed [app](https://benwinding.github.io/react-admin-import-csv/#/posts). If you delete everything and reimport from file, i.e. import without collision, you'll see that the notification shows 'Imported', without the name of the file. On my side it'll be '导入的%{fname}'. But if you import a file with collision, the notification displays correctly the name of the file. 
I still believe it's relevant to what I've mentioned at the beginning.

**Comment by benwinding** [comment]
Hi @peter-jerry-ye,
Wow this thing is difficult to fix!
- So I cannot replicate the issue you're describing, can you send a video of the issue and exact steps to reproduce it? 
![Peek 2020-11-22 20-42](https://user-images.githubusercontent.com/11782590/99901017-70780e00-2d03-11eb-8e34-9e031605b80e.gif)
- Also I've updated some dependencies, maybe that fixed it?
- I'm still not sure that it's a state related problem, as the `translation` and `notify` are both synchronously executed:
 https://github.com/benwinding/react-admin-import-csv/blob/701ea3e9dc0632a49bca5a1fd9bd4c2cb04df8f5/src/main-csv-button.tsx#L144-L149
- It's more likely that the `fname` variable is null for some reason, but I'm not sure how to reproduce the error.
- You can make a PR to fix the issue if you're able to find it...
Thanks,
Ben

**Comment by peter-jerry-ye** [comment]
@benwinding You've already replicated the issue. I should correct my description: On my side it'll be '导入的' without the file name, i.e. fname is null. The fact I saw %{fname} was due to the previous bug.

I'm not sure what you mean by you don't know how to reproduce the error: you've already done that.

What I've found was that if you add `console.log(fileName)` after line 98 of `main-csv-button.tsx`, you'll see that `fileName` remains empty, which is why I said it should be related to `useState`. 

In fact, you should've noticed it yourself, as you've placed `resetVars()` on line 146 which `setFileName('');` before the `fileName` is used on line 147, while you can still have the file name displayed normally in the case there's a conflict.

I'm not sure if my description is clear enough. I would love to make a PR to fix it, just as I've done last friday. In fact a simple solution is convert `fname` from a state to a simple variable passed along all function, but I might not be free during the week.

**Comment by benwinding** [comment]
Ahhh, okay I think I understand the issue now. `${fname}` is empty in certain conditions right?. Well, I think it's finally fixed!

![Peek 2020-11-22 22-59](https://user-images.githubusercontent.com/11782590/99903771-775c4c00-2d16-11eb-95b1-35aa297c15ea.gif)

You were correct it was due to the `setState` being used in an asynchronous function. This kind of [breaks the rules of react hooks](https://reactjs.org/docs/hooks-rules.html), and is better suited to the `useEffect` hook. The implementation has been changed to use the `File` object as the trigger to cause the rest of the effects, via `setFile(file)`.

https://github.com/benwinding/react-admin-import-csv/blob/a07aec59d258a9652061ab662df8b665f54b4743/src/main-csv-button.tsx#L157-L160

https://github.com/benwinding/react-admin-import-csv/blob/a07aec59d258a9652061ab662df8b665f54b4743/src/main-csv-button.tsx#L56-L116

Let me know if this works!
Cheers,
Ben

**Comment by peter-jerry-ye** [comment]
Well done! The issue is fixed. Thank you very much.
